apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - sealed-service-gatekeeper-secret.yaml
patches:
  - path: gatekeeper-values-dev.yaml
    target:
      kind: HelmRelease
      name: service-gatekeeper
