apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: skaha
  namespace: skaha-system
spec:
  interval: 5m
  chart:
    spec:
      chart: skaha
      version: 0.8.1
      sourceRef:
        kind: HelmRepository
        name: science-platform
        namespace: skaha-system
  values:
    replicaCount: 1
    skaha:
      namespace: skaha-system
    deployment:
      hostname: canfar.ral.uksrc.org # change this!
      skaha:
        skahaTld: "/arc"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "500m"

        maxUserSessions: "3"
        sessionExpiry: "345600"
        defaultQuotaGB: "10"
        # Space delimited list of allowed Image Registry hosts. These hosts should match the hosts in the User Session images.
        registryHosts: "images.canfar.net"
        # The group name to verify users against for permission to use the Science Platform. Group must exist in the group provider.
        usersGroup: "ivo://skao.int/gms?prototyping-groups/mini-src/platform-users"

        # Set to an administrative group. Used to determine if the current user can bypass Harbor image validation.
        # adminsGroup: "ivo://skao.int/gms?prototyping-groups/mini-sr|c/platform-users"
        adminsGroup: "ivo://cadc.nrc.ca/gms?skaha-admins"

        # Group for users to preempt headless jobs. Group must exist in the group provider. (Optional)
        headlessGroup: "ivo://skao.int/gms?prototyping-groups/mini-src/platform-users"

        # Array of groups allowed to set the logging level. Group must exist in the group provider. (Optional)
        loggingGroups:
          - "ivo://skao.int/gms?prototyping-groups/mini-src/platform-users"

        # The Resource ID of the Service that contains the Posix Mapping information
        # posixMapperResourceID: "ivo://espsrc.iaa.csic.es/posix-mapper"
        posixMapperResourceID: "ivo://cam.uksrc.hpc.cam.ac.uk/posix-mapper"
        # posixMapperResourceID: "ivo://uksrc.org/posix-mapper"

        # URI or URL of the OIDC (IAM) server
        oidcURI: https://ska-iam.stfc.ac.uk/
        gmsID: ivo://skao.int/gms

        registryURL: https://spsrc27.iaa.csic.es/reg

        # Optionally mount a custom CA certificate
        extraVolumeMounts:
          - mountPath: "/config/cacerts"
            name: cacert-volume

        # Create the CA certificate volume to be mounted in extraVolumeMounts
        extraVolumes:
          - name: cacert-volume
            secret:
              defaultMode: 420
              secretName: canfar-tls-secret

    # Default is a PersistentVolumeClaim to the Local Storage.
    storage:
      service:
        spec:
          persistentVolumeClaim:
            claimName: skaha-pvc

    secrets:
      # Uncomment to enable local or self-signed CA certificates for your domain to be trusted.
      # posix-manager-cacert-secret:
      #   ca.crt: <base64 encoded ca crt>

    # An omission equals true, so set this explicitly to false as we already installed it.
    posixmapper:
      install: false
      # Supports all of the posix-mapper/values.yaml options here.
