---
apiVersion: v1
kind: ConfigMap
metadata:
  name: srcnet01-cluster-config
  namespace: capi-self
data:
  values.yaml: |
    # Must match the name of the (sealed) secret in credentials.yaml
    cloudCredentialsSecretName: srcnet01-credentials

    kubernetesVersion: 1.30.2
    machineImageId: 6f8e1b6f-3e5e-45fe-adb2-f35ba2909396

    clusterNetworking:
      externalNetworkId: 57add367-d205-4030-a929-d75617a7c63e
      internalNetwork:
        networkFilter:
          name: portal-internal

    controlPlane:
      machineFlavor: vm.ska.cpu.general.small
      machineCount: 3

    nodeGroups:
      - name: workers
        machineFlavor: vm.ska.cpu.general.medium
        machineCount: 3
        autoscale: true
        machineCountMin: 1
        machineCountMax: 6        

    addons:
      # Use the cilium CNI
      cni:
        type: cilium

      # Enable the monitoring stack
      monitoring:
        enabled: true

      # Disable NFD and the NVIDIA/Mellanox operators
      nodeFeatureDiscovery:
        enabled: false
      nvidiaGPUOperator:
        enabled: false
      mellanoxNetworkOperator:
        enabled: false
