#####
## NOTE
##
## This file is sealed, commited and pushed as part of the bootstrap process
## The unsealed version should NEVER be committed to git
#####

---
apiVersion: v1
kind: Secret
metadata:
  name: uksrc-ral-stage-cluster01-credentials
  namespace: capi-self
  annotations:
    # Allow the sealed secret controller to take over this secret after bootstrapping
    sealedsecrets.bitnami.com/managed: "true"
stringData:
  clouds.yaml: |
    clouds:
      openstack:
        auth:
          auth_url: "https://openstack.stfc.ac.uk:5000/v3"
          application_credential_id: "f9429efd49d44d898eba7382a3be8664"
          application_credential_secret: "sQFnO6OWaEOh5l0vxQ2A5HWg3KDiBz1SJPWyzAaR26l4NHI0QNHVmukvd6ySkrHAQDPbMUP2-CxK2JbtPZytXw"
          project_id: "ffe9f53bf77b47948393fc0c8bd27f1b"
        region_name: "RegionOne"
        interface: "public"
        identity_api_version: 3
        auth_type: "v3applicationcredential"

