---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: jupyterhub
spec:
  chart:
    spec:
      chart: jupyterhub
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
  releaseName: jupyterhub
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  interval: 5m
  valuesFrom:
  - kind: Secret
    name: jupyterhub-secret-config
    valuesKey: client_secret
    targetPath: hub.config.GenericOAuthenticator.client_secret
  - kind: Secret
    name: jupyterhub-secret-config
    valuesKey: client_id
    targetPath: hub.config.GenericOAuthenticator.client_id
  values:
    proxy:
      service:
        type: ClusterIP

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        # cert-manager.io/cluster-issuer: letsencrypt-staging
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - jupyterhub.ral.uksrc.org
      pathSuffix: ""
      pathType: Prefix
      tls:
        - hosts:
          - jupyterhub.ral.uksrc.org
          secretName: jupyterhub-ingress-cert

    hub:
      allowNamedServers: true
      namedServerLimitPerUser: 5
      activeServerLimit: 3
      networkPolicy:
        enabled: false

      config:
        Authenticator:
          enable_auth_state: true
          allow_all: true
        JupyterHub:
          authenticator_class: generic-oauth
        BinderSpawner:
          auth_enabled: true
        GenericOAuthenticator:
          login_service: "SKA-IAM"
          oauth_callback_url: https://ral.uksrc.org/jupyterhub/hub/oauth_callback
          authorize_url: https://ska-iam.stfc.ac.uk/authorize
          token_url: https://ska-iam.stfc.ac.uk/token
          userdata_url: https://ska-iam.stfc.ac.uk/userinfo
          scope:
            - openid
            - profile
            - email
            - offline_access
          username_key: preferred_username
          userdata_token_method: GET
          userdata_params: { "state": "state" }
          allowed_groups:
            - "src/uksrc"
          manage_groups: true

        baseURL: https://jupyterhub.ral.uksrc.org/

        db:
            pvc:
              storageClassName: csi-cinder

      # We install the kubernetes client here so that we can use it to
      # detect weather the cluster has any GPU nodes, allowing us to show/hide
      # GPU nodebook profiles automatically.
      args:
        - bash
        - -c
        - "pip install kubernetes && jupyterhub --config /usr/local/etc/jupyterhub/jupyterhub_config.py --upgrade-db"
      extraConfig:
        # Add user profiles dynamically based on cluster hardware
        customspawner.py: |
          from kubespawner import KubeSpawner
          from kubernetes import client, config

          def build_profiles(spawner: KubeSpawner):
            profiles = [
              {
                "display_name": "Minimal environment",
                "description": "To avoid too much bells and whistles: Python.",
                "default": True,
              },
              {
                "display_name": "Datascience environment",
                "description": "If you want the additional bells and whistles: Python, R, and Julia.",
                "kubespawner_override": {
                  "image": "quay.io/jupyter/datascience-notebook:2024-08-05"
                },
              },
            ]

            config.load_incluster_config()
            api = client.CoreV1Api()
            nodes = api.list_node().items
            has_gpu = lambda node: node.metadata.labels.get("nvidia.com/gpu.present", "") == "true"
            if any(map(has_gpu, nodes)):
              profiles.append({
                "display_name": "Pytorch environment",
                "description": "The official Jupyter Pytorch + CUDA image. Requires a GPU compatible notebook server.",
                "kubespawner_override": {
                  "image": "quay.io/jupyter/pytorch-notebook:cuda12-pytorch-2.4.0",
                  "extra_resource_limits": {
                    "nvidia.com/gpu": "1",
                  },
                },
              })
            else:
              profiles.append({
                "display_name": "Pytorch environment",
                "description": "The official Jupyter Pytorch.",
                "kubespawner_override": {
                  "image": "quay.io/jupyter/pytorch-notebook:pytorch-2.4.0",
                },
              })

            return profiles

          c.KubeSpawner.profile_list = build_profiles

    # Pre-pullers are not useful when profile list
    # is built dynamically
    prePuller:
      hook:
        enabled: false
      continuous:
        enabled: false

    singleuser:
      memory:
        limit: 1G
        guarantee: 1G

      cpu:
        limit: 0.5
        guarantee: 0.5

      storage:
        dynamic:
          storageClass: csi-cinder
        capacity: 1Gi
        extraVolumes:
          - name: jupyterhub-cephfs-static-pv
            persistentVolumeClaim:
              claimName: jupyterhub-ceph-volume
          - name: jupyterhub-userspace-pv
            persistentVolumeClaim:
              claimName: jupyterhub-userspace-pvc             
        extraVolumeMounts:
          - name: jupyterhub-cephfs-static-pv
            mountPath: /home/jovyan/shared
            readOnly: true
          - name: jupyterhub-userspace-pv
            mountPath: /home/shared-users
            readOnly: false
            mountPropagation: HostToContainer      

      defaultUrl: /lab
      # Defines the default image
      image:
        name: quay.io/jupyter/minimal-notebook
        tag: "2024-08-05"

