apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmchart.yaml
  - helmrelease.yaml
  - secret.yaml
  - extra-rbac.yaml
  - jupyterhub-pvc.yaml
  
