---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: ska-src-gatekeeper
spec:
  values:
    gatekeeper:
      services:
        - route: "/echo"
          namespace: ska-src-gatekeeper-echo
          prefix: "http://"
          service_name: "ska-src-gatekeeper-echo"
          ingress_host: "gatekeeper.ral.uksrc.org"
          port: 8080
          uuid: "d921efbf-71a9-47cc-8527-69d1a0a50d8b"
        - route: "/soda"
          namespace: ska-src-soda
          prefix: "http://"
          service_name: "ska-src-soda"
          ingress_host: "gatekeeper.ral.uksrc.org"
          port: 8080
          uuid: "51d69ecd-e47a-44ca-9b5a-59c90a6dd631"
