---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ska-src-gatekeeper-secret
  namespace: ska-src-gatekeeper
spec:
  encryptedData:
    site_capabilities_gatekeeper_client_id: AgAYQt9lNdZACb3JEylUbHIJLeSXaxI6Tb3l/X4RroZlXvzosOumaiQX/4+N7koG8ekE1JUGWTo6gDPCqSFESC/bEPkhUKMwrZD42Kb5EI5OSk6rvvGZ4UhacsxYlbF6fBtRz+/IRry9y+s5O52wOxH+aQcDsIFwvIik8pIruGjcZvwMEAv88tMasSrJvPsNmqErM3WwPZ1sLPkIdhULflQMUt1bAsMERSbUE/isyRaBpT0+2wVyPha0uxwM9cYApy97iCCQPTBYRqQLxXSNNREKB81zWQ026sDT5tHNYbcF4vWIpgIBDAr+3V+v0BLQTe7yR5y1zrP/WDUfBnGx2VSHHR7cSH1CW1+HT46pgB9xIYToDCg1C+IzsHd7BjKSX/lDHTQLz9yVcL7k/C/QcQX6F1TFmk1bP8+EHsS8Ae3/8hOeXQDWNYsWkLXNr+GuuUOeA05Awh2czzGRcRcsgJHG+XVrk0BBZ/TBZ8UWjqAvCTSwhlX9rEwGEpJMiIQNEpN74WMhm7DMgCRV6EEKRFIfdq4i/nJ6//MQSOpKcuGqr6qqTkvCCcCgucp7rTAjDNKviwf6WqsJG8Up7eFoed5cQUFSWw1w2PhUPWpc2guim5Yr9lo6nNKIBYw4EuWvnALPTlviqY5SoE1JOLGJWQyrNtHD9cbf6zDElNckKqkhsPV8bEYqbWPBdcF5ehfFFlgP+nej+YXs66BC5KLW7AVStX/+UkbZ9KKnqabKpqyNlLkf7Vs=
    site_capabilities_gatekeeper_client_secret: AgAcLC09nvOQmhHlDGs+1WlRCfa1K/PtWa5a+14DDz4XwjgkmSFPf28LCVQ/7o0cuq3FbcI9XfuaZwKKW66AbKLP+z9kaX+3iCnrONEsTdCscU0sMS4dvdFPSIuLd3SQyBxWXZncza0k+Ko6jD6iuD2bRmAx6gr7zfZRH9b30RK5KCMKG5DYeg1rmlqKU7VXFCqqlUT5iaWOYYt/MF36AjMU4MAt7wUnGSM7gS54gPtCWM1ZXSsZnsRfdaE+fYXYSkS5EVPAXX/93ar/cYcBKYkHY+6E/IrZrX0oG4uO2jlNeeeaCraZHzIxtnDKIN2YQsKXBiwBRRzU/tMOW9DMZnkuttAEA6wE93lSlAJYmfzm1STcezbQmpBq6pgiJPYiveMQgdFNsCXROKW1zNpadnPHHTeGX8haCH/koGBsvT/cUJMnJuPIxwGlnS/rvY1XFQLQM+buFcc148yCCQyB2nDeqhU9MFVYzfdO2/WilJKddhwc7vxJk7EOOihe9iXgUE89qKiZlVnv8EGepvfswdj1ohCGD1hgCEgVkGV+c20dbcuV6OCAlTpiEmR/WS8eM4IQ4yNokkmoSoqO7r5F+Nqi3HuuVFaKQPfQ3lmzZNzSz72IUwgePm4p3ErwqZL3KxFvqqbnc+cQmDLoT8c04IJ28pIGS2XHQat8rd6hMwWIuARYZDZkCz3SXEzqskDfJiLoGMbycwytQF+sIgWs5flS8HhnJ7DAPa83u4nfnU0kX1KUN4pzUzX30vFtLY0LNiuL4hJHBrJSlHZzlJRvVmUH9kaCwUomxYXouOxbI4W0nKWjmIIveQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: ska-src-gatekeeper-secret
      namespace: ska-src-gatekeeper
    type: Opaque
