---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ska-src-gatekeeper-secret
  namespace: ska-src-gatekeeper
spec:
  encryptedData:
    client_id: AgCrWpLITHCkFFbIPO/yMx0V8vwLmMFaoUoqll7HIZrXq0KqRL/d+tilY5jWtv8irwptXOLGisSiLnToh1XPDOzrgXeU8wDTS7gh4SVtHKH9obkrmC0cwdqV9iJbKolI3bxF6TBUXJGaaQPCo+VwMBsrtUaIvJZKv+3Tu6F3jX2F8JwCXQdZinnpx66NSYeNj2d0fP2v1jM499QcM0wW7G7oC/E2nYKBSrp9oIm3MJH9PCBvppjYiL58zY5O414DO38wF0QMcKFwA5smeQv42arWx+rGGyw2bzER4xTnIsF3bvZLSnpRpuI02jeuKqjK8bROfoyrF46zC2MoijBX1KO56b8TnwntcVENk00mcU+lR3F+nEWzOf17QKM5o6vnHUE6SQCmYMBrydCS59g3+od9wwQMJhvM38FWTpS4OOVko1vt3viImfFrVnOUu5QTWSbxe+UtAn5h+KCCoPiyHmng5733Z2VCljGCbZhkSzeTdiU5fRg3BzzURSxHIUNPVrWaxLJfTLcM2Pkwu1KHoYQq2e+GcqC/OxkuYIKoB1RuX4jQUHSHayZhiIKfPNyU4+9dXQmeTFwNfQ+yaEgEzGW8a5z4LXSKSfJu6GHjWqs0o5VA4KPf53054HqG/ONG/PasIUluZamSoJ4RYVbVf12LVcGhuNHmTTy4EiTZpYPgHUYFCPEv6t0NPprGwz6KG7RxnIttOIDMPWK5rQTM60waxXQ797K3s0DZW+ivEVG1MibsowM=
    client_secret: AgBNuZcKNJiwMajRlHnUVHeO1iUL3SkL+VbXzi5fMDhZ37uXOa3mOQocwVZ26ghyunDlyuuVkBGjAHJZOfdKs+Iw28Xpz2JAvFu1z4VZifbve8gTHNrjEtY3Ws5tL9TemB1bSefk+VCuakyOiLX3Ts9ai1U2weIRlCMyMr6t00NDqsPGa+jDIv9Ldn1XcPGvc+4XGR4d9rCRGp5tKL3+YNPv/Ye81mMpracXL+MYo7/t8OhfUS4iue7aGf9L0mz3oNTkMKXqnA705wqyyTAhiIdLiVXZmChfJSZ/ktbyOO8Y7TpVwfyYWS/vlohCnVURx0YPlTNjHPLz2m8tz+JQbglgSkFvb/qc8b/fWMN0xeclT+vbnreO4PckWHcGkKn+wGLaqR+HLn2Go6sVn14oud8Nj0fF8grMMTJ3ko3oLk8PbYN/rcAaFvq3wyBbQUjqw8+fzNTOf8UuOIvqdDVdguSj8P7Q6McImBWeiGlRtJwxflKKAwvQDtKWc05s+3c70CGVLgU5ddquVPp+JmAJLtDdyRhrL566643tCPDTnzPKk72oIiVkUfwNPqR/JqevMuO6jMPQGYf95YHiqa7nQfW+SSESk7UAeu2xFlnO8DWQwH8t9HJWOdrhpa4zNHySD3dMs0V3+i127974E/R8FUGZp+MYl+lWnjAZMiHdJ3DTWZevfY0TddOpbtZQRgmkg/WXC8vEyUM2hg+3R9fBqS3qYTuYWW/tH+0Caf/trCidUcGa98au3pvu989i5J6PkjaRHcGgtlAritJmGwDfMPtXLQYNwiEoZO4U5HH64WyfNZjpEgtEcQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: ska-src-gatekeeper-secret
      namespace: ska-src-gatekeeper
    type: Opaque
