apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gatekeeper-ingress
  namespace: ska-src-gatekeeper
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-gatekeeper-prod
spec:
  ingressClassName: gatekeeper-nginx
  rules:
  - host: ""  
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: ska-src-service-gatekeeper-ingress-nginx-controller
            port:
              number: 8080
  tls:
  - hosts:
    - "gatekeeper.ral.uksrc.org"
    secretName: gatekeeper-cert