apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - gitrepository.yaml
  - helmrelease.yaml
  - gatekeeper-certificate.yaml
patches:
  - target:
      kind: HelmChart
      name: Chart.yaml
    patch: |-
      - op: remove
        path: /dependencies/0