---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: cluster-api-operator
  namespace: capi-operator-system
spec:
  chart: cluster-api-operator
  version: 0.14.0
  sourceRef:
    kind: HelmRepository
    name: cluster-api-operator
  interval: 1h
