apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-ui-config
  namespace: skaha-system
data:
  values.yaml: |
    replicaCount: 1
    skaha:
      namespace: skaha-system
    deployment:
      hostname: canfar.ral.uksrc.org
      storageUI:
        resources:
          requests:
            memory: "500M"
            cpu: "500m"
          limits:
            memory: "500M"
            cpu: "500m"
        backend:
          defaultService: cavern
          services:
            cavern:
              resourceID: "ivo://canfar.ral.uksrc.org/cavern"
              nodeURIPrefix: "vos://canfar.ral.uksrc.org~cavern"
              userHomeDir: "/home"
              features:
                batchDownload: false
                batchUpload: false
                externalLinks: false
                paging: false
        gmsID: ivo://skao.int/gms
        oidc:
          uri: https://ska-iam.stfc.ac.uk/
          clientID: PLACEHOLDER_CLIENT_ID
          clientSecret: PLACEHOLDER_CLIENT_SECRET
          redirectURI: https://canfar.ral.uksrc.org/storage/oidc-callback
          callbackURI: https://canfar.ral.uksrc.org/storage/list/
          scope: "openid profile offline_access"
        registryURL: https://spsrc27.iaa.csic.es/reg
        identityManagerClass: org.opencadc.auth.StandardIdentityManager
        extraVolumeMounts:
          - mountPath: "/config/cacerts"
            name: cacert-volume
        extraVolumes:
          - name: cacert-volume
            secret:
              defaultMode: 420
              secretName: canfar-tls-secret
        # Default theme is the SRC one.
        themeName: src
