apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: storageui
  namespace: skaha-system
spec:
  interval: 5m
  chart:
    spec:
      chart: storageui
      version: 0.2.5
      sourceRef:
        kind: HelmRepository
        name: science-platform
        namespace: skaha-system
  values:
# Tell Kubernetes to spin up multiple instances.  Defaults to 1.
    replicaCount: 1
    skaha:
      namespace: skaha-system
    deployment:
      hostname: canfar.ral.uksrc.org # Change this!
      storageUI:
        # OIDC (IAM) server configuration.  These are required
        oidc:
          # Location of the OpenID Provider (OIdP), and where users will login
          uri: https://ska-iam.stfc.ac.uk/

          # The Client ID as listed on the OIdP.  Create one at the uri above.
          clientID:
            valueFrom:
              secretKeyRef:
                name: storage-ui-credentials
                key: clientID
              

          # The Client Secret, which should be generated by the OIdP.
          clientSecret:
            valueFrom:
              secretKeyRef:
                name: storage-ui-credentials
                key: clientSecret

          # Where the OIdP should send the User after successful authentication.  This is also known as the redirect_uri in OpenID.
          redirectURI: https://canfar.ral.uksrc.org/storage/oidc-callback

          # Where to redirect to after the redirectURI callback has completed.  This will almost always be the URL to the /science-portal main page (https://example.com/science-portal).
          callbackURI: https://canfar.ral.uksrc.org/storage/list

          # The standard OpenID scopes for token requests.  This is required, and if using the SKAO IAM, can be left as-is.
          scope: "openid profile offline_access"

        # ID (URI) of the GMS Service.
        gmsID: ivo://skao.int/gms

        # Dictionary of all VOSpace APIs (Services) available that will be visible on the UI.
        # Format is:
        backend:
          defaultService: cavern
          services:
            cavern:
              # resourceID: "ivo://cam.uksrc.hpc.cam.ac.uk/cavern"
              resourceID: "ivo://canfar.ral.uksrc.org/cavern"
              nodeURIPrefix: "vos://canfar.ral.uksrc.org~cavern"
              userHomeDir: "/home"
              # Some VOSpace services support these features.  Cavern does not, but it needs to be explicitly declared here.
              features:
                batchDownload: false
                batchUpload: false
                externalLinks: false
                paging: false

        # Optionally mount a custom CA certificate
        extraVolumeMounts:
        - mountPath: "/config/cacerts"
          name: cacert-volume

        # Create the CA certificate volume to be mounted in extraVolumeMounts
        extraVolumes:
        - name: cacert-volume
          secret:
            defaultMode: 420
            secretName: canfar-tls-secret

    # secrets:
      # Uncomment to enable local or self-signed CA certificates for your domain to be trusted.
      # science-portal-cacert-secret:
        # ca.crt: <base64 encoded ca.crt blob>
