apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: storage-ui
  namespace: skaha-system
spec:
  interval: 5m
  chart:
    spec:
      chart: storageui
      version: 0.2.5
      sourceRef:
        kind: HelmRepository
        name: science-platform-client
        namespace: skaha-system
  valuesFrom:
    - kind: Secret
      name: storage-ui-credentials
      valuesKey: clientID
      targetPath: deployment.storageUI.oidc.clientID
    - kind: Secret
      name: storage-ui-credentials
      valuesKey: clientSecret
      targetPath: deployment.storageUI.oidc.clientSecret        
  values:
    replicaCount: 1
    skaha:
      namespace: skaha-system
    deployment:
      hostname: canfar.ral.uksrc.org
      storageUI:
        oidc:
          uri: https://ska-iam.stfc.ac.uk/.
          redirectURI: https://canfar.ral.uksrc.org/storage/oidc-callback
          callbackURI: https://canfar.ral.uksrc.org/storage/list
          scope: "openid profile offline_access"
        gmsID: ivo://skao.int/gms
        backend:
          defaultService: cavern
          services:
            cavern:
              # resourceID: "ivo://cam.uksrc.hpc.cam.ac.uk/cavern"
              resourceID: "ivo://canfar.ral.uksrc.org/cavern"
              nodeURIPrefix: "vos://canfar.ral.uksrc.org~cavern"
              userHomeDir: "/home"
              # Some VOSpace services support these features.  Cavern does not, but it needs to be explicitly declared here.
              features:
                batchDownload: false
                batchUpload: false
                externalLinks: false
                paging: false

        # Optionally mount a custom CA certificate
        extraVolumeMounts:
        - mountPath: "/config/cacerts"
          name: cacert-volume

        # Create the CA certificate volume to be mounted in extraVolumeMounts
        extraVolumes:
        - name: cacert-volume
          secret:
            defaultMode: 420
            secretName: canfar-tls-secret

    # secrets:
      # Uncomment to enable local or self-signed CA certificates for your domain to be trusted.
      # science-portal-cacert-secret:
        # ca.crt: <base64 encoded ca.crt blob>
