---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: storageui
  namespace: skaha-system
spec:
  interval: 5m
  chart:
    spec:
      chart: storageui
      version: 0.2.5
      sourceRef:
        kind: HelmRepository
        name: science-platform-client
        namespace: skaha-system
  valuesFrom:
    - kind: Secret
      name: storage-ui-credentials
      valuesKey: clientID
      targetPath: deployment.storageUI.oidc.clientID
    - kind: Secret
      name: storage-ui-credentials
      valuesKey: clientSecret
      targetPath: deployment.storageUI.oidc.clientSecret        
  values:
    replicaCount: 1
    skaha:
      namespace: skaha-system
    deployment:
      hostname: canfar.ral.uksrc.org
      storageUI:
        resources:
          requests:
            memory: "500M"
            cpu: "500m"
          limits:
            memory: "500M"
            cpu: "500m"
        backend:
          defaultService: cavern
          services:
            cavern:
              resourceID: "ivo://canfar.ral.uksrc.org/cavern"
              nodeURIPrefix: "vos://canfar.ral.uksrc.org~cavern"
              userHomeDir: "/home"
              features:
                batchDownload: false
                batchUpload: false
                externalLinks: false
                paging: false
        gmsID: ivo://skao.int/gms
        oidc:
          uri: https://ska-iam.stfc.ac.uk/
          redirectURI: https://canfar.ral.uksrc.org/storage/oidc-callback
          callbackURI: https://canfar.ral.uksrc.org/storage/list/
          scope: "openid profile offline_access"
        registryURL: https://spsrc27.iaa.csic.es/reg
        identityManagerClass: org.opencadc.auth.StandardIdentityManager
        extraVolumeMounts:
          - mountPath: "/config/cacerts"
            name: cacert-volume
        extraVolumes:
          - name: cacert-volume
            secret:
              defaultMode: 420
              secretName: canfar-tls-secret
        # Default theme is the SRC one.
        themeName: src