---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: storageui
  namespace: skaha-system
spec:
  interval: 5m
  chart:
    spec:
      chart: storageui
      version: 0.2.5
      sourceRef:
        kind: HelmRepository
        name: science-platform-client
        namespace: skaha-system
  valuesFrom:
    - kind: ConfigMap
      name: storage-ui-config
    - kind: Secret
      name: storage-ui-credentials
      valuesKey: clientID
      targetPath: deployment.storageUI.oidc.clientID
    - kind: Secret
      name: storage-ui-credentials
      valuesKey: clientSecret
      targetPath: deployment.storageUI.oidc.clientSecret
  values:
    replicaCount: 1
    skaha:
      namespace: skaha-system
    deployment:
      hostname: canfar.ral.uksrc.org # Change this!