apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: preparedata

resources:
  - ../../base
  - cavern-user-space.yaml
  - preparedata-rse-storage.yaml

# Helm chart definition with values overlay
helmCharts:
  - name: rabbitmq
    repo: oci://registry-1.docker.io/bitnamicharts
    namespace: preparedata
    releaseName: rabbitmq
    # base values file
    valuesFile: ../../base/values-rabbitmq.yaml
    # overlay values file that will override the base
    #additionalValuesFiles:
    #  - values-rabbitmq.yaml