---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi
  namespace: csi-ceph-system
spec:
  chart:
    spec:
      chart: ceph-csi-cephfs
      sourceRef:
        kind: HelmRepository
        name: ceph-csi
  interval: 1m
  releaseName: ceph-csi
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    cleanupOnFail: true
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: Secret
      name: csi-cephfs-secret
      valuesKey: userID
      targetPath: secret.userID
    - kind: Secret
      name: csi-cephfs-secret
      valuesKey: userKey
      targetPath: secret.userKey
  values:
    cephconf: |

    csiConfig:
