---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: ceph-csi
  namespace: csi-ceph-system
spec:
  chart: ceph-csi-cephfs
  version: "3.11.0"
  sourceRef:
    kind: HelmRepository
    name: ceph-csi
  interval: 1m0s
