---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ska-src-gatekeeper-secret
  namespace: ska-src-gatekeeper
spec:
  encryptedData:
    site_capabilities_gatekeeper_client_id: AgCdE/vxpqkY13FFhXKZsIWmXL5SLT94kEKu2x+k9fOEvSGIWs5wFbfi0FsGo14n3lg6goNQJuy06CcBh0HT0Oy7LqZCbxj9Jmb/Z+1CpinCW8h4kmre/gxNbf5U4F6gLDE3PbZf9d6l83ybBBnBVrxHbCe8vAHX9AvLoSHfG1UW5y/ktbstHsnZtHkWrRqhQzypRBoh2r9dhwLi7auiePnJ5pNQS0Uv2Tq+VA2vzKZl8upffmQceEFNe58iKF1fmqTjIoSdxzraqlW1R4B0bT3M50TK+ssAjkarybrk/PFHmRJbie6zRbVJd9II9ZD7KfjTuS6JRloD2mBaCuXoH2Tw25m2ZSP2Z5HGCz/WEos/mdthM1jbLaEugwFq7n2wid69ryye/lUQ8nyGqJ3l9fY9alCnkikH5isXFRmG7tS1mCRETmCZF9vXNZ4HOt/BlpqE77bxoiPmOALpoNjzRArjFBgDOnwxLoNajf259sUghnascEjkNFI4gS7KOnYMKqZECW7Wy2NQIGwzkUiz2VXgOh+FEAWtZeAk6rKUP7+klZIi3qP5NjZwtxZ6Azo2HdDxZz/AHkrP6gmiFjrwURRL8WV2zgUaE3Bg2d3hSFhkUB7JGZ2/xy1ht4Q7tL8ZL4ypl+e5Xp/fVukXhRvYc4T54BjlYTt7jnUPzPLPmmSMaOFoxfjUSEIg+DFA0vx5mMJy/W/FosuP+v7wB3Ufm3h62POYX6Rz97eUZ1h//6Wgy0npnPU=
    site_capabilities_gatekeeper_client_secret: AgBrLh2NeZ6Kv1HJmelhCAc/CQZXMPvbLqr1ewtV2F8gjk/RDp4+/1VBqNF710hQK7STE0VDDNHsqn8HibK1C5e78zjx76lrUiidQ8buDQnwkgX7+wBAsdGf7MlLyo0SYkKSt+/OZlYoPwY+yoGxoyttgO8yjPNUU8VQAaPw1YcBHyXXkUJJiYfmuw3fUDK1DBA1bSNe94v3pjfm0jFv7cuxfPssJ0IllzW6mJDw1E16zQ2UuCcfKboO0tCVKLkL6RwI8oODFjfOEKcjLYckOoMd0cXH07L7ck6n0nwclfhRGGyh8KkVRwKGNLrdduQy4RrZGbA5I+lz1PKNEKVCxnoaF9CQcD6c0pQvJKJsZlRIZgAWPwcYVHczPHkhJFvf92W3VU+D+we/qXybJ4ZjR1xE+ARyLNvrkKt1d314vaZv86uQCt9cK53s8grRv0J2XelgtQPHLic+29/fKHnQMtu6ryhEwAmrVyLEIl2Xtge4QCL0r8g0dk49XTFGCr4BQ6Jt7vo3B0YYHm6pq4yOM+WVgZ/45VBF8W/aglVtL1piJ3hb3v8Y2bjKRhcluJnCuUDawKTXLv+O8WmKrC6jMZpd61DZM3C8I2+cjovJgYOO47Px7masTdwwm+zFAuwNykEhNH/1DglSp7ZIA4deYKb7Uf3QdOmhpwRxQ6zJfX+I+DcVgjFDKUqbmMF2NC9UdVmlHSWJQYrmH2B81JCai7YPpIBYBDK3jiOfG+i0zzpgdKUeek10K/HaZN0IyPWTlSWTqGzoL6eeD+pmybcrbYoM5khXtf5S+Dp/ERSn4ulXAo9GQGJqqw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: ska-src-gatekeeper-secret
      namespace: ska-src-gatekeeper
    type: Opaque
