---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: ska-src-gatekeeper
spec:
  values:
    gatekeeper:
      services:
        - route: "/echo"
          namespace: ska-src-gatekeeper-echo
          prefix: "http://"
          service_name: "ska-src-gatekeeper-echo"
          ingress_host: "gatekeeper.ral.uksrc.org"
          port: 8080
          uuid: "e98b8c67-7f06-47e6-9618-5cf471483fd5"
        - route: "/soda"
          namespace: ska-src-soda
          prefix: "http://"
          service_name: "ska-src-soda"
          ingress_host: "gatekeeper.ral.uksrc.org"
          port: 8080
          uuid: "3b59c8b6-7717-4f58-9b63-8ee3c0e89276"
    ingress-nginx:
      controller:
        replicaCount: 1
        service:
          type: ClusterIP
          loadBalancerIP: ""