apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - gatekeeper-secret.yaml
patches:
  - path: gatekeeper-values.yaml
    target:
      kind: HelmRelease
      name: ska-src-service-gatekeeper
  - target:
      kind: Ingress
      name: gatekeeper-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: gatekeeper.ral-stage.uksrc.org
      - op: replace
        path: /spec/tls/0/hosts
        value:
          - gatekeeper.ral-stage.uksrc.org