---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: cluster-api-janitor-openstack
  namespace: capi-janitor-system
spec:
  chart: cluster-api-janitor-openstack
  version: 0.6.2
  sourceRef:
    kind: HelmRepository
    name: cluster-api-janitor-openstack
  interval: 1h
