---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Ingress
      name: grafana-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: grafana.ral.uksrc.org
      - op: replace
        path: /spec/tls/0/hosts
        value: 
          - grafana.ral.uksrc.org        
  - target:
      kind: Ingress
      name: prometheus-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: prometheus.ral.uksrc.org
      - op: replace
        path: /spec/tls/0/hosts
        value: 
          - prometheus.ral.uksrc.org        