# This already exists and does not need to be created
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: cavern-workload-cephfs
#   labels:
#     name: cavern-workload-cephfs
# spec:
#   accessModes:
#   - ReadWriteMany
#   capacity:
#     storage: 10Gi
#   csi:
#     driver: cephfs.manila.csi.openstack.org
#     volumeHandle: cavern-workload-cephfs
#     nodeStageSecretRef:
#       name: csi-manila-credentials
#       namespace: openstack-system
#     nodePublishSecretRef:
#       name: csi-manila-credentials
#       namespace: openstack-system
#     volumeAttributes:
#       shareID: d8395514-8896-4817-9193-4e550e9ac483
#       shareAccessID: e58edeab-8b81-41ae-8946-3da3e471cdf9

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: userspace-pvc
  namespace: preparedata
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeMode: Filesystem
  # volumeName should be same as PV name
  volumeName: cavern-workload-cephfs

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rse-share-cephfs
  labels:
    name: rse-share-cephfs
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  csi:
    driver: cephfs.manila.csi.openstack.org
    volumeHandle: rse-share-cephfs
    nodeStageSecretRef:
      name: csi-manila-credentials
      namespace: openstack-system
    nodePublishSecretRef:
      name: csi-manila-credentials
      namespace: openstack-system
    volumeAttributes:
      shareID: b73f8f41-8287-4e8b-b057-4bebcde73701
      shareAccessID: f22c4921-241e-4948-98e3-62ea85a9b478

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: preparedata-rse-pvc
  namespace: preparedata
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeMode: Filesystem
  # volumeName should be same as PV name
  volumeName: rse-share-cephfs