apiVersion: v1
kind: Service
metadata:
  labels:
    app: preparedata-api
  name: preparedata-api
  namespace: preparedata
spec:
  ports:
  - name: 8000-8000
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: preparedata-app
  type: ClusterIP
