---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: uksrc-ral-stage-cluster-credentials
  namespace: capi-self
spec:
  encryptedData:
    clouds.yaml: AgAw1NllZQ5GNyxpr9EKGvt9zVTRTfRzu1J9PFjCJInLMmeaq2mw9jSS6h7nHZKsEqthd58GWhb/6LpySM2X2KB0EZ/5ow7t/UeQ2m6F4QDqOt82Qk5O1z5eUC8EDxcekOThc+uwKYKfL14anD9aCFL8l550D/gGVR2WpreZhSd9WOWtHoBRnUvy18UqSCOymm5JGCkTMBjgHl2DgIjjpUnay51zXWenvVcxKHfzAVQE4gKIiig/jzCT2P2kJlQNnmw3T+0DhkKH5ZTCFQ/cpwgw1X+jEeqkqJEpgCFKbrMF4MQbDmZmwQzXxqyLf7SyapAnfjFWAiSZiTle4IGccNLUUBANhSJ10YuJ6xV6FLTXd712pfD/fV8YXJQsd+DpBekpo7lkx8mi8sb2Vu8tdrEmsrw+xOHV2mb9C6EWwMPJhXg+iLm+kr5uCCOxgiGu32aJEgRzPa8pJOxe2koPENfqokHMG55SheejgLTBu0HpeUL25y/hGjdYA14ljUnNv1mHC0KOnofDPLN3kPBpPsBELuKqW3GsoVlaIDSMM9K3iCOx4HaFCP8CtdQIn5w9uOC7oqzmBjf2ZZrrrfSQ7tNqTv2J06BG4Y0/KK3mwHEgE0BSS8oCW9OYDwk+S0WauJpXcPO6WJhPw9bf91shuhAigxhQFkczznLeGkUe+CxInT9kpSbkxn50DqRDRfSbXhWDD6ZnDYc0pMztXzTkTecOxw/i+0/dzyCwKZSJZVdE4+0+fd6qIh/raen7XZExHidf57T6Mhr3C7v9gWldvWmncEWcWB0cGFPn5ieVOv8iCISxL9CYYzDIz/8va+1KU8ZqVzDuJ8VBr0dPsjRoIHoBRVbyI1D6EMxgDOzuET5gpb6m19zV1lkC0ihgEjMVoSY6DYK0YAPjF2a+x5g1ek5xekrfFzfL9nZz3cDLsPyBWpTO1vh2u5JuGsjCCNSFW7nFCqOIQdDf5xp6T+7uLA6K0TJ0p8+OavSoRBqR4vyryV7lAPAhEb9g1/4tnPbHsB95BIwGMbx9mBL8e7/N/I84EA4TD5xoChXtwAqhlSe6Gz4hpJqTizr/t5UPRnS71mO2wvy/1vtjHPKcAc8gKcWQAISiEXXT7PZu+k6a8zzs6ahB0Nl5/eAd0t8AcTPwneilogOM+21M4iAvdZB0be9MpuFAwPYtFtEVmt4elcbEWmMuLZr0nKi8+FeMzHvhz2tvDSIlYmC822niCGe+
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: uksrc-ral-stage-cluster-credentials
      namespace: capi-self
