---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/soda
  - ../../apps/jupyterhub
  - jupyterhub-seecret.yaml
patches:
  - path: jupyterhub-values.yaml
    target:
      kind: HelmRelease
      name: jupyterhub