---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: soda-values.yaml
    target:
      kind: HelmRelease
      name: soda-release
  - target:
      kind: PersistentVolume
      name: soda-cephfs-static-pv
    patch: |-
      - op: replace
        path: /spec/csi/volumeAttributes/clusterID
        value: 2660d5ed-e7ef-4950-a051-c84a0b4e78b0