apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: soda-release
  namespace: ska-src-soda
spec:
  values:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        # - soda.ral.uksrc.org
        - soda.130-246-81-193.sslip.io
      tls:
        - hosts:
          - soda.ral.uksrc.org
          secretName: soda-ingress-cert