resources:
  - configmap.yaml
  - credentials-sealed.yaml
  - ../../components/flux
  - ../../components/sealed-secrets
  - ../../components/cluster-api
  - ../../components/cluster
  
# After bootstrap add the apps and services here
  - ../../components/cert-manager/issuers.yaml
  - ../../infra/ceph-share/overlays/ral-stage
  - ../../infra/monitoring/overlays/ral-stage
  - ../../apps/soda/overlays/ral-stage
  - ../../apps/gatekeeper/overlays/ral-stage
  - ../../apps/jupyterhub/overlays/ral-stage
  # - ../../apps/canfar/overlays/ral-stage
  
# Patch the Helm release for the cluster to update the release name
#   This ensures we get nicely named resources in OpenStack
# We also add our configmap to the values sources for the release
patches:
  - target:
      kind: HelmRelease
      name: cluster
    patch: |-
      - op: replace
        path: /spec/releaseName
        value: uksrc-ral-stage

      - op: add
        path: /spec/valuesFrom/-
        value:
          kind: ConfigMap
          name: uksrc-ral-stage-cluster-config
          valuesKey: values.yaml
