---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: csi-cephfs-secret
  namespace: csi-ceph-system
spec:
  encryptedData:
    userID: AgAO8FuogaTAy3uJ1ym5WXsIPnGfk2fetvnZIvSxjLFo08KEZe+0Ul+KYSOoWdg8ZrdD1LIs1g+YNfPPuURsj/OyEMYdopmoLgeVJcDFyxp5xJ5N0YtuP9XPR2Yosq0hs7xWWS3YAhs7PWIX55pqhfQ0kABjXLaJuY9drMcwZGADDhoClIAivCkJbgiIAwjKTtB764nnhuByIKCSvh5kmIW9jZ3LziMnKKexWspUtXx/FzLTFAxahaFPIo3ZQtWukg+eeGYY2BbjbBui/Hgn0y6vbKvflyfEaqBhNJr6LkpBcQIXVRB2sGj6yqv2uQSpY2TIXxxWcHshTqB3mv63N4UKV1vbfKW/feqhEOKNpeQY95EjuKVbrh6JlDnKS1qyqKZkahSmE5XTOj7gWr6X8nCglJsDOeJxDmPF6DfCoR2yZxsKuAKx+wh2PGEF2kQ6/jBTqMIgWRVDDqA3I3Gw/wJTPu/LcgSS+XwbXT2OWSFNu/q4eJjtPPGkwjlBiB2tDcvHJ1rdlLukJk0lreTFCLBC7v8G7tN0dI7/v0aejTB/JVAyHCwBxY2YF3lKJoCI1lgLPz7zeT5Zx9ASrIfev1fbFbU3K2+YdG8dgYwWjOHEAaPzlaQ6iFQUFTlvdosbIQQlFsLFa/OQbaRucUjdXZODaJnDWEJD9/0J/YB1vBTclvfXBr5UnH4bgKqZoo9y1GQjm3NMvBE=
    userKey: AgCcf4DGLnRFK8RfVdBViej602zoS5dy46JeJjY1f6ko+Fl+IDsLRuf9dvdnXpuvp3HhXXDclzVx11El0YdSM56UinD5dxZFF7adBCBuAawBYS5Oz+oyV8F9wL7Df2RZdgUhjxW/SIxJazMwHI0/w8mjLOlOcLU4hRNhMchwNMiZM4N9pcTAOI6bDtb3OHvn6hZ1iG5Qb8NA7DzfWLvslOS/2/7Z40kMy2BRz1GQrv29jyj+gznAmmignKwwV+g54NiBOGeioA4kNkHaCccey020Zu9vSGH6xGxhc19S2SJg1GPCe49T5Fm6TgE5Ezcf7juUn8YDGPfPS9wcjTrGhIVB/QeTMCdBTeoCwhtWOzs0HBhtrNF/IkpzeItEHycheoCQK9RSP+EmipcisjVegWGm+LpEre3+hxGtP7PpWARsoQAHiZXCJTtU6ZogVUmBBzE4c8DR8vxdX3P7UH4y5jHE1smbCa+sruvcWB1hdAUZobjA252LPyy4oDbnF6Lb9lgVRARSbNzLkiaNqjzGjbhmTlb+n9NdUlH3UwB0DyRnPQmps9lm3s2L/EwlpurUV9mLO1BqphVNslWpAPS/gZzZ4s2LcouRQBw6sKSmwPJX74lJmEvJUUTsb83v4MrA7AM1+2vUUw9PodxX5fwGf5iCknmO/K5jo59coV3oiciZ094YikzZojnElRFNIh76esu8YdR8fvKO+GPP1JR+JuK64H9eXxE+VZ4rBkUlSB9Y6uMZK3FkhK2i
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: csi-cephfs-secret
      namespace: csi-ceph-system
    type: Opaque
