---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gatekeeper
  namespace: gatekeeper
spec:
  url: https://gitlab.com/api/v4/projects/60950975/packages/helm/stable
  interval: 1m0s
