---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: ska-src-gatekeeper
spec:
  chart:
    spec:
      chart: ska-src-dm-da-service-gatekeeper
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
      valuesFiles:
        - values.yaml
  releaseName: gatekeeper
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  interval: 5m


