apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: service-gatekeeper
  namespace: gatekeeper-dev
spec:
  chart: "etc/helm"
  version: "0.1.7"
  sourceRef:
    kind: GitRepository
    name: gatekeeper-repo
  interval: 5m
