apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: service-gatekeeper
  namespace: gatekeeper-dev
spec:
  interval: 5m
  chart:
    spec:
      # chart: etc/helm
      sourceRef:
        kind: GitRepository
        name: gatekeeper-repo
        namespace: gatekeeper-dev
      chart: etc/helm
      interval: 5m
      version: "0.0.2"

  valuesFrom:
    - kind: Secret
      name: service-gatekeeper-secret
      valuesKey: values.yaml
  values:
    deployment_echo:
      namespace: service-gatekeeper-echo-dev
      image: harbor.srcdev.skao.int/ska-src-dm-da-service-gatekeeper/service-gatekeeper-echo:1.0.1

    gatekeeper:
      namespace: gatekeeper-dev
      ingress_proxyBodySize: 5000m
      ingress_proxyBuffering: "off"
      ingress_proxyRequestBuffering: "off"
      iam_token_endpoint: https://ska-iam.stfc.ac.uk/token
      permissions_api_plugin_authz_endpoint: https://permissions.srcdev.skao.int/api/v1/authorise/plugin/
      site_capabilities_api_get_service_by_id_endpoint: https://site-capabilities.srcdev.skao.int/api/v1/services/
      site_capabilities_gatekeeper_client_id: "<from selead-secret>"
      site_capabilities_gatekeeper_client_secret: "<from selead-secret>"
      site_capabilities_gatekeeper_client_scopes: site-capabilities-api-service
      site_capabilities_gatekeeper_client_audience: site-capabilities-api
      services_cache_ttl: 3600
      services:
        - route: "/echo"
          namespace: service-gatekeeper-echo-dev
          prefix: "http://"
          service_name: "service-gatekeeper-echo"
          ingress_host: ""
          port: 8080
          uuid: "<generated-service-uuid>"

