apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrelease.yaml
  - sealed-service-gatekeeper-secret.yaml
  - gitrepository.yaml
  - helmchart.yaml
  