apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: jupyterhub
spec:
  values:
    ingress:
      hosts:
        - jupyterhub.ral.uksrc.org
      tls:
        - hosts: 
          - jupyterhub.ral.uksrc.org
          secretName: jupyterhub-ingress-cert

    hub:
      config:
        GenericOAuthenticator:
          oauth_callback_url: https://jupyterhub.ral.uksrc.org/hub/oauth_callback
          authorize_url: https://ska-iam.stfc.ac.uk/authorize
          token_url: https://ska-iam.stfc.ac.uk/token
          userdata_url: https://ska-iam.stfc.ac.uk/userinfo
        baseURL: https://jupyterhub.ral.uksrc.org/

###################### Update the following section to use the Coral PVC mounts######################

      storage:
        dynamic:
          storageClass: csi-cinder
        capacity: 1Gi
        extraVolumes:
          - name: jupyterhub-cephfs-static-pv
            persistentVolumeClaim:
              claimName: jupyterhub-ceph-volume
        extraVolumeMounts:
          - name: jupyterhub-cephfs-static-pv
            mountPath: /home/jovyan/shared
            readOnly: true        