{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: soda-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.proxyBodySize | quote }}
    nginx.ingress.kubernetes.io/proxy-buffering: {{ .Values.ingress.proxyBuffering | quote }}
    nginx.ingress.kubernetes.io/proxy-request-buffering: {{ .Values.ingress.proxyRequestBuffering | quote }}
spec:
  rules:
  # - host: {{ .Values.ingress.host }}
  - host: soda.ral.uksrc.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ska-src-soda
            port:
              number: 8080
  ingressClassName: nginx
{{- end }}
