apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
  # - host: "grafana.130-246-80-45.sslip.io" 
  - host: "grafana.130-246-81-193.sslip.io" 
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: kube-prometheus-stack-grafana
            port:
              number: 80
  tls:
  - hosts:
    - "grafana.ral.uksrc.org"
    secretName: grafana-ingress-cert


