apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: canfar-certificate
  namespace: skaha-system
spec:
  secretName: canfar-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "canfar.ral.130-246-80-185.sslip.io" 
