apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: base
  namespace: skaha-system
spec:
  interval: 5m
  chart:
    spec:
      chart: base
      version: "0.3.3"
      sourceRef:
        kind: HelmRepository
        name: science-platform
        namespace: skaha-system
  values:
    skaha:
      namespace: skaha-system
    skahaWorkload:
      namespace: skaha-workload
    traefik:
      install: true
      ports:
        web:
          port: 80
          containerPort: 80
          loadBalancerIP: 130.246.80.185
          exposedPort: 80
          name: "http-web"
        websecure:
          port: 443
          containerPort: 80
          loadBalancerIP: 130.246.80.185
           name: "https-websecure"
          exposedPort: 443
            
          
        