resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmchart.yaml
  - helmrelease.yaml
  - pv-pvc-manila.yaml
  - canfar-ingress.yaml
  - posix-mapper/helmrelease.yaml
  - skaha/helmrelease.yaml
  - cavern/helmrelease.yaml
  - science-portal/helmrelease.yaml
  # - storage-ui/helmrelease.yaml

   