apiVersion: v1
kind: PersistentVolume
metadata:
  name: skaha-workload-pv
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  capacity:
    storage: 10Gi
  storageClassName: csi-cinder
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: cinder.csi.openstack.org
    volumeHandle: 4b486634-b493-4468-9aac-22b8fd65e7af
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skaha-workload-cavern-pvc
  namespace: skaha-workload
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: csi-cinder
  resources:
    requests:
      storage: 10Gi