apiVersion: v1
kind: PersistentVolume
metadata:
  name: skaha-pv
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  capacity:
    storage: 10Gi
  storageClassName: csi-cinder
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: cinder.csi.openstack.org
    volumeHandle: 6d689c6a-9851-4e1b-a86a-1031ce3f1629
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skaha-pvc
  namespace: skaha-system
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: csi-cinder
  resources:
    requests:
      storage: 10Gi