---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cavern-cephfs
  labels:
    name: cavern-cephfs
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  csi:
    driver: cephfs.manila.csi.openstack.org
    volumeHandle: cavern-cephfs
    nodeStageSecretRef:
      name: csi-manila-credentials
      namespace: openstack-system
    nodePublishSecretRef:
      name: csi-manila-credentials
      namespace: openstack-system
    volumeAttributes:
      shareID: d8395514-8896-4817-9193-4e550e9ac483
      shareAccessID: e58edeab-8b81-41ae-8946-3da3e471cdf9

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cavern-workload-cephfs
  labels:
    name: cavern-workload-cephfs
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  csi:
    driver: cephfs.manila.csi.openstack.org
    volumeHandle: cavern-workload-cephfs
    nodeStageSecretRef:
      name: csi-manila-credentials
      namespace: openstack-system
    nodePublishSecretRef:
      name: csi-manila-credentials
      namespace: openstack-system
    volumeAttributes:
      shareID: d8395514-8896-4817-9193-4e550e9ac483
      shareAccessID: e58edeab-8b81-41ae-8946-3da3e471cdf9

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skaha-pvc
  namespace: skaha-system
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeMode: Filesystem
  # volumeName should be same as PV name
  volumeName: cavern-cephfs

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skaha-workload-cavern-pvc
  namespace: skaha-workload
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeMode: Filesystem
  # volumeName should be same as PV name
  volumeName: cavern-workload-cephfs


