---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: flux2
  namespace: flux-system
spec:
  chart: flux2
  version: 2.14.0
  sourceRef:
    kind: HelmRepository
    name: fluxcd-community
  interval: 1h
