---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Ingress
      name: grafana-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        # value: grafana.cam.uksrc.org
        value: grafana.128-232-226-44.sslip.io
  - target:
      kind: Ingress
      name: prometheus-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        # value: prometheus.cam.uksrc.org
        value: prometheus.128-232-226-44.sslip.io