---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: jupyterhub
spec:
  chart:
    spec:
      chart: jupyterhub
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
      valuesFiles:
      - values.yaml
      - values-jupyterhub.yaml
  releaseName: jupyterhub
  valuesFrom:
  - kind: Secret
    name: jupyterhub-secret-config
    valuesKey: client_secret
    targetPath: hub.config.GenericOAuthenticator.client_secret
  - kind: Secret
    name: jupyterhub-secret-config
    valuesKey: client_id
    targetPath: hub.config.GenericOAuthenticator.client_id
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  interval: 5m
