---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: jupyterhub
spec:
  chartRef:
    kind: HelmChart
    name: jupyterhub
  releaseName: jupyterhub
  valuesFiles:
    - values.yaml
    - values-jupyterhub.yaml
  valuesFrom:
  - kind: Secret
    name: jupyterhub-secret-config
    values:
      - key: client_secret
        targetPath: hub.config.GenericOAuthenticator.client_secret
      - key: client_id
        targetPath: hub.config.GenericOAuthenticator.client_id
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  interval: 5m
