# ---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-staging
#   namespace: cert-manager
#   acme:
#     server: https://acme-staging-v02.api.letsencrypt.org/directory
#     email: sm2921@cam.ac.uk
#     privateKeySecretRef:
#       name: letsencrypt-staging
#     solvers:
#       - http01:
#           ingress:
#             ingressClassName: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sm2921@cam.ac.uk
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
      - http01:
          ingress:
            ingressClassName: base-traefik