apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: jupyterhub
spec:
  values:
    ingress:
      hosts:
        - host: jupyterhub.ral-stage.uksrc.org
      tls:
        - hosts: 
            - jupyterhub.ral-stage.uksrc.org

    hub:
      config:
        GenericOAuthenticator:
          oauth_callback_url: https://ral-stage.uksrc.org/jupyterhub/hub/oauth_callback
          authorize_url: https://ska-iam.stfc.ac.uk/authorize
          token_url: https://ska-iam.stfc.ac.uk/token
          userdata_url: https://ska-iam.stfc.ac.uk/userinfo
        baseURL: https://ral-stage.uksrc.org/jupyterhub