---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jupyterhub-secret-config
  namespace: jupyterhub
spec:
  encryptedData:
    client_id: AgAcI+/kYgbZXCrixYeTqmX+I2JXEtPICRW4lrR9FVEEmqiOQlQUcJZu28M0L9LYhlNGBY3rP71PjCL/Ae/EriuqGwIXVKCCOHHJaygoDCvYV4mxef+R+/qW56InGsZMeLXuFXB7k6pgqMlpE5t/B/uJii8JCdqonScLlRBXbZYc6a+rmI0AJ9q2eZPWJXZwYurH8TmaUmbsNw8rbrtdhJnflaeS+ducaN4Yd3IC47P0irrCCNgGhNWvmRv4ZeMrD9ezAGEUdwOHemXK9S7VzHqJ69VOnG1CWGa2NiytTwonDFUlgyBR6n7yf1XomTK4QHZ1X7/cmJp1clfjPr0c7QBUVxf7fz3wC1ngqFmAAX0qNpksdQkVawBeF11omDQ6nPOatV3bjyioGapL6zPvdHHGNsv+peSBTVsLr0h39sqEYKhqge5ijFwhy9yPMPYyoyvOxmp9wMKEu2GMvY34l6YEp63tWw4W2kHSOkDlB8Lb6RBBX9WF+AH80M+kUEByPnwCGmySXhhtMxhRCeMIFSsdQcbCFfXv4IjtMusL/EpiO5xXgwzhBtc+oe4uYeCIaUm8h4kwqizeXC+ytIqn/Ky5sgN1jhT5JHn+VOD5Ezk34hWX9U1/2hM0QOBLVnOZ0lwx1exUte5i3Ood1AHaEG5knrdKY/bMvIZYgt0RcMiOAOf5B+mB5zDnY74JXdKBwOItvcjTgdS+uo+vaH4JRS0ykHpEk4JMxjx9LfMBwOgR9l5S65c=
    client_secret: AgAfUNn8DdMH89hwyZ2eQMdksgu1Szhx+wGGJwnvmfcnUOOZlgXK5oV7LFEK/HyvMi6FLnOoJl/GHQhTY1juryes5bAr05K/OvrHr8tEo/jvw+PD08+lhqknGAVEZjaR+Ra+FAPdab6u0+9Eym4RhJgj+famE+yJt0P1bZn4CA14XD1U4yUY4BzHny2dIiZe9PxDQDuM4BVMJO03baKFbYAsWomzP/WpQjGHo28npn56VFaQuoKsS6cj2pDJvH93nt/+90/kSsMutNTc/fQPb1xCRfRXnudcMRKMRVuPidBDxpw7jpb9eyegxAxLfttNCN4Zk2e5j2hjnQ01fI/jJEu4paP2aR0t/KbpA7oMNj0qZmaNHrA6OsSX6TDv6CNz0z+wegKPFk3BtkHWmc+yZEyAc0wwuEEdUS++yPhHOjO7oMP0mnU6a3IFFSwQm2HYHK1tK97Oyi1ijU0siXz4QJUTENuR6xqNP7vzbGgffvaNoCr5yi+rU37Z73RpE7psBUIUIr/Lqm7h7wzIbr4BGpYiMFcRGDkW/1EKwlYowm3vdGnNkEhHn3jM1MiI4ZfQEaOBJSv9s7HACxQIjMOpylnxklwFm0cLM5Da/NLc567TRXu3k/+e8XEFB6fsPy2akQcCL2YlYAIBm1m7uM6taQ4dZJyprrkpyCdRQzXhAa7NX4Eyms8X65gv+otv0Oe3cJpfJWcmW6SexkPGsngqCsxNW5SN61AqivrIE3BxOV5c9KPv8ybePV9C2w1gLEdyN5Fboqj5Qv/1mk4kXOwU58VQpVr5Sb1EMO5Pa+AADMtQ/EyIpEYR2n8=
  template:
    metadata:
      creationTimestamp: null
      name: jupyterhub-secret-config
      namespace: jupyterhub
    type: Opaque
