---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: scienceportal
  namespace: skaha-system
spec:
  interval: 5m
  chart:
    spec:
      chart: scienceportal
      version: 0.3.1
      sourceRef:
        kind: HelmRepository
        name: science-platform
        namespace: skaha-system
  valuesFrom:
    - kind: ConfigMap
      name: science-portal-config
    - kind: Secret
      name: oidc-credentials
      valuesKey: clientID
      targetPath: deployment.sciencePortal.oidc.clientID
    - kind: Secret
      name: oidc-credentials
      valuesKey: clientSecret
      targetPath: deployment.sciencePortal.oidc.clientSecret
  values:
    replicaCount: 1
    skaha:
      namespace: skaha-system
    deployment:
      hostname: canfar.ral.uksrc.org # Change this!
