apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: scienceportal
  namespace: skaha-system
spec:
  interval: 5m
  chart:
    spec:
      chart: scienceportal
      version: 0.3.1
      sourceRef:
        kind: HelmRepository
        name: science-platform
        namespace: skaha-system
  values:
    replicaCount: 1
    skaha:
      namespace: skaha-system
    deployment:
      hostname: canfar.ral.uksrc.org # Change this!
      sciencePortal:
        themeName: src
        tabLabels:
          - Standard
          - Advanced
        resources:
          requests:
            memory: "500M"
            cpu: "500m"
          limits:
            memory: "500M"
            cpu: "500m"
        # OIDC (IAM) server configuration.  These are required
        oidc:
          # Location of the OpenID Provider (OIdP), and where users will login
          uri: https://ska-iam.stfc.ac.uk/

          # The Client ID as listed on the OIdP.  Create one at the uri above.
          clientID:
            valueFrom:
              secretKeyRef:
                name: oidc-credentials
                key: clientID
              

          # The Client Secret, which should be generated by the OIdP.
          clientSecret:
            valueFrom:
              secretKeyRef:
                name: oidc-credentials
                key: clientSecret
            

          # Where the OIdP should send the User after successful authentication.  This is also known as the redirect_uri in OpenID.
          redirectURI: https://canfar.ral.uksrc.org/science-portal/oidc-callback

          # Where to redirect to after the redirectURI callback has completed.  This will almost always be the URL to the /science-portal main page (https://example.com/science-portal).
          callbackURI: https://canfar.ral.uksrc.org/science-portal/

          # The standard OpenID scopes for token requests.  This is required, and if using the SKAO IAM, can be left as-is.
          scope: "openid profile offline_access"
        # The Resource ID of the Service that contains the URL of the Skaha service in the IVOA Registry
        skahaResourceID: ivo://espsrc.iaa.csic.es/skaha
        gmsID: ivo://skao.int/gms
        registryURL: https://spsrc27.iaa.csic.es/reg
        identityManagerClass: org.opencadc.auth.StandardIdentityManager
        
        # Optionally mount a custom CA certificate
        extraVolumeMounts:
        - mountPath: "/config/cacerts"
          name: cacert-volume

        # Create the CA certificate volume to be mounted in extraVolumeMounts
        extraVolumes:
        - name: cacert-volume
          secret:
            defaultMode: 420
            secretName: canfar-tls-secret



        # The logo in the top left.  No link associated, just the image.  This can be relative, or absolute.
        # Default is the SRCNet Logo.
        #logoURL: /science-portal/images/SRCNetLogo.png

    # secrets:
      # Uncomment to enable local or self-signed CA certificates for your domain to be trusted.
      # science-portal-cacert-secret:
        # ca.crt: <base64 encoded ca.crt blob>
