apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: preparedata
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - preparedata-userspace-volume.yaml
  - preparedata-rse-volume.yaml  
  - rmq-helmrelease.yaml
  - rmq-helmchart.yaml
  - rmq-helmrepository.yaml
