---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: preparedata-rse-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: csi-cephfs-secret
      namespace: csi-ceph-system
    volumeAttributes:
      "clusterID": "clusterid"
      "staticVolume": "true"
      "rootPath": "/ska"
    volumeHandle: preparedata-rse-pv
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: preparedata-rse-pvc
  namespace: preparedata
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: preparedata-rse-pv