apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: preparedata
spec:
  interval: 5m
  chart:
    spec:
      chart: base
      version: "15.3.3"
      sourceRef:
        kind: HelmRepository
        name: rabbitmq
        namespace: preparedata
    interval: 1m0s

