---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: preparedata
spec:
  interval: 5m
  chart:
    spec:
      chart: rabbitmq
      sourceRef:
        kind: HelmRepository
        name: rabbitmq
        namespace: preparedata
  releaseName: rabbitmq
  upgrade:
    remediation:
      retries: 3
  rollback:
    timeout: 5m
    disableWait: false
    disableHooks: false
    recreate: false
    force: false
    cleanupOnFail: false

