apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: preparedata

resources:
  - ../../base
  - preparedata-userspace-volume.yaml
  - preparedata-rse-volume.yaml
patches:
  - path: rmq-values.yaml
    target:
      kind: HelmRelease
      name: rabbitmq