---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - helmrelease.yaml
  - ingress.yaml
patches:
  # - path: traefik-values.yaml
  #   target: 
  #     kind: HelmRelease
  #     name: science-platform
  - target:
      kind: Ingress
      name: canfar-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: canfar.ral-stage.uksrc.org
      - op: replace
        path: /spec/tls/0/hosts
        value:
          - gatekeeper.ral-stage.uksrc.org        
