---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  # - ingress.yaml
patches:
  - target:
      kind: Ingress
      name: canfar-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: canfar.ral-stage.uksrc.org
      - op: replace
        path: /spec/tls/0/hosts
        value:
          - gatekeeper.ral-stage.uksrc.org
  - target:
      kind: HelmRelease
      name: base
    patch: |-
      - op: replace
        path: /spec/values/traefik/service/spec/loadBalancerIP
        value: "130.246.215.245"
  - target:
      kind: HelmRelease
      name: cavern
    patch: |-
      - op: replace
        path: /spec/values/deployment/hostname    
        value: "canfar.ral-stage.uksrc.org"
      - op: replace
        path: /spec/values/deployment/cavern/resourceID
        value: ivo://canfar.ral-stage.uksrc.org/posix-mapper
      - op: replace
        path: /spec/values/deployment/cavern/posixMapperResourceID
        value: ivo://canfar.ral-stage.uksrc.org/posix-mapper
  - target:
      kind: HelmRelease
      name: posix-mapper
    patch: |-
      - op: replace
        path: /spec/values/deployment/hostname
        value: "canfar.ral-stage.uksrc.org"
      - op: replace
        path: /spec/values/posixMapper/resourceID
        value: ivo://canfar.ral-stage.uksrc.org/posix-mapper
  - target:
      kind: HelmRelease
      name: scienceportal
    patch: |-
      - op: replace
        path: /spec/values/deployment/hostname
        value: "canfar.ral-stage.uksrc.org"
      - op: replace
        path: /spec/values/deployment/sciencePortal/oidc/redirectURI
        value: "https://canfar.ral-stage.uksrc.org/science-portal/oidc-callback"
      - op: replace
        path: /spec/values/deployment/sciencePortal/oidc/callbackURI
        value: "https://canfar.ral-stage.uksrc.org/science-portal/"
  - target:
      kind: HelmRelease
      name: skaha
    patch: |-
      - op: replace
        path: /spec/values/deployment/hostname
        value: "canfar.ral-stage.uksrc.org"
      - op: replace
        path: /spec/values/deployment/skaha/posixMapperResourceID
        value: ivo://canfar.ral-stage.uksrc.org/posix-mapper
  - target:
      kind: HelmRelease
      name: storage-ui
    patch: |-
      - op: replace
        path: /spec/values/deployment/hostname
        value: "canfar.ral-stage.uksrc.org"
      - op: replace
        path: /spec/values/deployment/storageUI/oidc/redirectURI
        value: "https://canfar.ral-stage.uksrc.org/storage/oidc-callback"
      - op: replace
        path: /spec/values/deployment/storageUI/oidc/callbackURI
        value: "https://canfar.ral-stage.uksrc.org/storage/list"
      - op: replace
        path: /spec/values/deployment/storageUI/backend/service/cavern/resourceID
        value: ivo://canfar.ral-stage.uksrc.org/cavern
      - op: replace
        path: /spec/values/deployment/storageUI/backend/service/cavern/nodeURIPrefix
        value: "vos://canfar.ral-stage.uksrc.org~cavern"