---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: base
  namespace: skaha-system
spec:
  values:
    traefik:
      service:
        spec:
          type: NodePort
          # loadBalancerIP: ""