---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: grafana-ingress.yaml
    target:
      kind: Ingress
      name: grafana-ingress
  - path: prometheus-ingress.yaml 
    target:
      kind: Ingress
      name: prometheus-ingress