---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cephfs-share-static-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: csi-cephfs-secret
      namespace: csi-ceph-system
    volumeAttributes:
      # optional file system to be mounted
      #      "fsName": "deneb-dev"
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "2660d5ed-e7ef-4950-a051-c84a0b4e78b0"
      "staticVolume": "true"
      "rootPath": "/ska"
    volumeHandle: cephfs-share-static-pv
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
