apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ska-src-service-gatekeeper
  namespace: ska-src-service-gatekeeper
spec:
  chart:
    spec:
      chart: etc/helm
      version: 0.0.1
      sourceRef:
        kind: GitRepository
        name:  ska-src-service-gatekeeper
        namespace: ska-src-gatekeeper
  interval: 1h
  valuesFrom:
  - kind: Secret
    name: ska-src-gatekeeper-secret
    valuesKey: site_capabilities_gatekeeper_client_id
    targetPath: gatekeeper.site_capabilities_gatekeeper_client_id
  - kind: Secret
    name: ska-src-gatekeeper-secret
    valuesKey: site_capabilities_gatekeeper_client_secret
    targetPath: gatekeeper.site_capabilities_gatekeeper_client_secret 
  values:
    deployment:
      namespace: ska-src-gatekeeper
      image: harbor.srcdev.skao.int/ska-src-dm-da-service-gatekeeper/service-gatekeeper-echo:1.0.1

    ingress:
      proxyBodySize: 5000m
      proxyBuffering: "off"
      proxyRequestBuffering: "off"

    gatekeeper:
      iam_token_endpoint: https://ska-iam.stfc.ac.uk/token
      permissions_api_authz_endpoint: https://permissions.srcdev.skao.int/api/v1/authorise/plugin/
      site_capabilities_api_get_service_by_id_endpoint: https://site-capabilities.srcdev.skao.int/api/v1/services/
      site_capabilities_gatekeeper_client_scopes: site-capabilities-api-service
      site_capabilities_gatekeeper_client_audience: site-capabilities-api
      services_cache_ttl: 3600
      services:
        - route: "/echo"                          # request route
          namespace: ska-src-gatekeeper           # namespace the service will run in, can be different to gatekeeper ns
          prefix: "http://"                       # usually http:// assuming SSL termination occurs upstream
          service_name: "ska-src-gatekeeper-echo" # to proxied address
          ingress_host: ""                        # Host domain the Ingress rules will apply to
          port: 8080
          uuid: ""                                # generated by the site capabilities catalogue, corresponding entry must exist in iam
