---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: soda-cephfs-static-pv
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 100Gi
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: csi-cephfs-secret
      namespace: csi-ceph-system
    volumeAttributes:
      "clusterID": ""
      "staticVolume": "true"
      "rootPath": "/ska"
    volumeHandle: soda-cephfs-static-pv
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
