---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soda-pvc
  namespace: ska-src-soda
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: soda-cephfs-static-pv