---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jupyterhub.hub.fullname" . }}
  namespace: jupyterhub
  annotations:
    # Allow the sealed secret controller to take over this secret after bootstrapping
    sealedsecrets.bitnami.com/managed: "true"  
stringData:
  client_id: 7703b3d9-2013-4745-8972-f0d7708a7227
  client_secret: ANa59tHB8OotS6cc9QH53uNVQY8Yr8qP83JytosVzz6cK3kfNRdmfkAVLsoXv629VI6k_yGqLz_y_nXfIM6qCO8
