apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: uksrc-cam-cloud-credentials
  namespace: capi-self
spec:
  encryptedData:
    clouds.yaml: AgCWYCBGttjHL2ApRrQvOWmMm08L2b8dkRmZbS9QmKi9ASzEh/O44Zt2cbvIuQcea8NiR9eFGpzQ7YrWKsGntDJKu/zPnO4j3XBZEFwepULfVFkJd1qfqPlQ9oPXEzLuwjX5ha3oQTJd0aL1byEnqsmKqkjHF88GCE7jHCcDVc+OELTQg5TallhSUC04HLGFwqpiYOiy9PkvtwrfMC0eqg3hESIv5/d/5uqPBffWE5KoGgGf0hbM3CKh7rgjtXumNUqKYfoIe5iqQCnJ8CKDMAM5jjRYUkklwue9Bniat3QIxSFuIvGZuMvaPNcjPxA5opztnmc5mJk4njeIazIFjGbwBQvG2/Moyy+54zvJrXD+KQvdQuYBgQqPwX5x4/S4APhdElt2yZBbZtgq4AwE1i2UEdnuDzJNh4tBigHjX975G+LgELFv+LlIbWzYkDI2/xcymJWOg6Vd8qBlfvOnY+ucHYnz48WOmXt0oGsJk5bAy9yoipW0Cfacf4JrsyIJUlheR3bbnYdqD05fM3WAj9LKesy+s5fMjqzVCx2Z5MBIFCOOUxBg5puqOf5mumArdM4YZE2WXqWXUP6M+X08QRyXROy65396BJz5JOLZvarAPKm6BVqr2Zsfy6aEPV3z4omF1DVOCyEeMBmLGBwv9eRj3AZFjAvvfUBEcdOpkTOfnjxj6dMsWR2LCF6R6/20kKF/+a0yJ0JjvBhsJqgDokW0DLjvAvsGOCnxSAVqok5UOvtE+Vqu5Bc5T2Or8dj065+l55uyBx+RJVDDxgzNME6B+LJ2b+ng4Oogus2N9YVTInHNKeilCvg6sv+loM+KUqDg0ZcQ3DoHaUBAiTw9pPPEHg7ozpJjxyZ86OwqfJlowG4J8RToFMK36FOarmhVDwvymPAhpHDQrbpxkJjiR4nEKZ0K+7s/i306vMGk9CYR8wfxVzy01EwJzr2ZRUXS20mEqqM5T0KDhZkTMpXRoddpQE36NhIyM0SEwVFbMgWexowl2OnHyL2kANxCmOBgTnkvuzQDe0a39jqoTkGqGZSMGyZIDQkOjKOje22OVzk/om4Yhvc8sLprF8aMXssgFMvY8oyT1iC/1lhRFCT70XOxzIHxuywm33cv/w1qWGMKvsaCBaruCTbZKC5gCiTnM8GRKyoEa8JFYWYlx5KdnGt+iZe441VYIJshYId3RzNtDZAX0/RdOsM7gne1HpnB9qE0NgTik1jM7VcNvnvazYaASiycn3dzNJOJMhY=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: uksrc-cam-cloud-credentials
      namespace: capi-self

