---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: uksrc-cam-cloud-credentials
  namespace: capi-self
spec:
  encryptedData:
    clouds.yaml: AgCmCsDDbfpFzZvwCE7zdc0wNP85FYFw7TjgbeSXEiGjqBar/jQhz5KPQtxTfNQZB6B8sveakV3aLplKU9zm521AUcmCtkhsRpfQQtDrjpqxzwL8AzFQDBTqGv/zUusHsqOH+7I2+qPhK9EFR54JvCFTjgCLXP/0zgwsaAjcsotpdlGVBCuh8aIwCEQUp74nK5tIX0K6rWzTwUFK0t5OwLyOBTMq5AO93yAZ/omdEu3X8dAfN19QdP2bqs2DBE0WwaBNlW+D84eWnqRpjXUVqvVG/GdAjkhAi8imDRLihKi5girH56uTBMBDmXCQQCsxCvqxRwbvKKyaGyxcP98zxz1coF9E70Dbml7r5wDxQWIgf6zVS1cFOhux7kSkeN8V14K8GLQPZVwxC3JVBu+7xo5CPw3tFVE0vbcfrIbYdcPahSNmhMBGdGaIG5zCJJFKlbqYCimT8/+/RSUnCs31ao5pSyRAr2jRZxC0ueUmMoJq6H4lolbLFbUE+vYFeTkiMOC8kJLB4SSzwLk5bi1kKCMPb6BKKzm9vM4zAaYGI25EKppxcNyNuPcK2hfvOWMM4YEyApYDi8H8Y0cwqkbM8G0cWs/SBrvZ5FpTMnmZqIfCGeFqcqbuaqLR2U/k32EFqdq52+ra7LntWfF8LmrxmhmqiS1xRKRI1uwnOQQN3xv6Ucb3jdYjZU/I1wYbSgFP0t9zX3P6B62I/cOBlWTwysnGK766e5TGCAq5T7rgTQamjJRAw2MloDh5Rba0OkdJtBGDHhhiVq5uyz6sioA+EQKI3p+AJRvfRKmqnHYKY1NlMiRchdy6WXifT677WzzWNTorUlvvdRBzQ67NxO6f8Uk4odR9IBo+a62pSa+BTQwvWGeQR72LnIjCvnX5E1HZCQKHioMwVqWsFSSsG+Me1D0UJd6e3UTqc7mObq2NmsOq6ZLln8clY8BTxoDgvyqE5bfl+YXvhysdZGzfJwwbHWUvearZX8fVImXVTWxTd9Yy5k3cWupcv6iAmATjzzIHF0am+dsdsguH4WueeD9GpyqQ6SbHdTnJVcVCZ2fYd9R6wasJhvB2cvNJq20N5LDAZw5fQOk+2D94Yea7vcQFlQQUQOvse3QBCJRmRuGZWOw5BnIYlR6OwgNJn1PJwqGLc4EAjLY1SOcXzDic9SacnBxD9tVIqhbQwGrRrX7JVrXfo+jF0aJPIXnzRZJXBs2QoQB3dz5/W1Xxzs485/AJ7EwFWOvUF9i0
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: uksrc-cam-cloud-credentials
      namespace: capi-self
