---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ceph-volume.yaml
patches:
  - path: soda-values.yaml
    target:
      kind: HelmRelease
      name: soda-release
