apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: soda-release
  namespace: ska-src-soda
spec:
  values:
    ingress:
      host: soda.ral-stage.uksrc.org
      tls:
        - hosts: 
          - soda.ral-stage.uksrc.org
          secretName: soda-ingress-cert      