---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/helmRelease.yaml
  - ../../base/gitRepository.yaml
  - ../../base/namespace.yaml

  - soda-pvc.yaml

patches:
  - path: soda-values.yaml
    target:
      kind: HelmRelease
      name: soda-release



# patches:
#   - path: soda-values.yaml
#     target:
#       kind: HelmRelease
#       name: soda-release
#   - target:
#       kind: PersistentVolumeClaim
#       name: soda-pvc
#     patch: |-
#       - op: replace
#         path: /spec/accessModes
#         value: 
#           - ReadWriteOnce
#       - op: replace
#         path: /spec/resources/requests/storage
#         value: 5Gi
#       - op: replace
#         path: /spec/storageClassName
#         value: csi-cinder
