apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soda-pvc
  namespace: ska-src-soda
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-cinder