---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: uksrc-cam-cluster-credentials
  namespace: capi-self
spec:
  encryptedData:
    clouds.yaml: AgCymBE5uL1v12OODJ76iRMuU687/bHGFknZZjqI1cr9QBZaibAEd7oFzKHuahVg7HeXKmFXO9FkwtR1sJepPtXrF1oiaZs5pMO7YFK0jztyHtQI6uY2Fm4cvLXdjlA0bv6wJufhlqFXn3wuBTTbU8wr11gsCAyoIxF7rJfVPyFo4umQdkUJVXexh9uZZXbOz8fREW82k/HrySo5hpCqeQH63/JFte1+rYcX2slG1pW3OFGRsl7yfAfHTenaIkP/cshoeqgjdvY25Q5csjIGQFEIsWAM4+cOmoMQuQAlOneEOjOdQeUlJrywWHazK3wvtTd3TWv2lZaPLc2LEGxI2Px1Zb7SFnb5F+EQffCcHQ8tY+FovTPX5ng2nh0TASW2myh/6/vKkoHjN+TrCF1IhF8NdexQd9A3DR317uRzQKxON6CpZL+y/r1QYBOYrTUn9SmXoidb7mzVNC5zzGdug22f6Ill1SEJ3BuVC7Z3eqQ3FRsT50DevQx5j/l5HOcKxzXm0aN8dmX4YwEuxGXe2MPZERGGbDvU1Y+bodmwN6pyza6uxvl94C+51SF7Ar0wno689tU2cO/jZuIQLMhUDqUuGaP+mtm7XM8RRSrs85lqJCyozDAMMrS+PsdVCmFz+Z2krPeXrHg0Y8o7ZJ4P5sphtX0m0SVZ4abvyYmkjvTzs+5RMT99rC5jsd05Jpou+h39DHs29tKhq5t4ot+igCkjkm6F73KB2Lfxyg+ChPFzOXIDVmO/3xFChajt4hLULlwNX3G9UcbU99Rl3wWCVgkwDxsyS003kjlI+WNrtoOONIMjlqA5n2usDk0OwpInH7+ErXRCfKYV3Q1msHnv1yx3jxbxOoT5B9ek5Opt19nFx0o/6cst9HJTmIVOPEeNiRUdN7B+pm5Hr8am6ll6Xa330tOF0Gyrvsjvu7J7+4FxnL6MGYUDI0ofYGkQJPlNJ7owmJuZQJvSw0FXENhW5gRzp72H+sWeD8QvQzshKctX94Hd4OId1JPDuotfirxsr6fW1YeNr2lHdS3TSjqyza9ci53IgF16qO2I6tbYBlqwcet4zvN8dZvsRQSbiGtMmd6DZ+cInxgmeGMTIjWbBh57qnVZ2bqjbczHJLmfYcRj7yZnxAhEHhdg8RkqupF4OJ2YCtfH8etv6kDQXJ4xl9XS1CG387YuXpLbClEualVBSioNKtDh3HVQrJlmAT+l6F7w5vhG/tyYB/990kwLrJDeqrBGMFxc
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: uksrc-cam-cluster-credentials
      namespace: capi-self
