---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: uksrc-cam-cluster-credentials
  namespace: capi-self
spec:
  encryptedData:
    clouds.yaml: AgBj0sBpVN9MF4XuNoPNgcCJNzJAcBWl6lFfSX7estkrc2G+OekuelYIFyK0WVUt6FFlV8DW8nODpcgNjcmTFNH1SWv2MAnqHGnww4Jj23/pOvJELEvcFG+3dQX1lo4Q6/esiNdh4nbLZ5Bd3GXqhPldgCysJIbgC1cr61Xhw7q1bf3+PQzq85J9cEECaaO9ntM0yjDuaxzABiSGkyam8B9AUNufaM0RAfoo9cuMWL7hp6DhCfZhAsDmm7uS4jvowj7lerX6QRw3U0bQC90QKMP249SiCsu7bAUDuZhJ4QqNkoG3YlOEMm9MsoCtqDKLMDrsdmNkee1+5PU/BpYlpjKqVYwgvwWxo9UT7R96tIikirAh55oNRWDNTDbJITz35RzLCN3GSl64HFwVKCMAUcpJWQHsGPMR9Xm1pozP0SQZv/wKPKBzZQTDT5jI1dEea41tu2wVfKFaZLUv/xyse34+F67AnLDypC3ouAeB0PG047WvvjTSi8ZgvZENKcVaxhG8c6R06OYb1xBT/pmU6TbWkTdt2ZpoTZ+NR/scmr/JhN8xo6UqXRgtSbo8YjBoPsKWOopfvJyDHfWgzqrwC1MHoKiUw3IDXQ9qA4yLEZIk/3fWN7I7955SJnppezY8ADlhqQAoWRBGzpXpZGO0h1BrsWJLJqLq/yRBi3LOsxG9FSwYzKVv2sNldaZHAhy+ybGV0hgkHHUIcsaNaT/rlJYKt9Ceqkdu7x99GQobE0e3HL1KAjRl6rbhQUEVctk2oOFWR3WhypQQu6ZFt/dyptZlroAab3+phDWQ3z5HTfIRtc7a2BJ89pCF2aD8bm/u8v4JLJC9R5XWROfbFH4ALjQd8ekwFnE/VTtNbANVkfpVXPG2IFnH8ZAf2Vbi4cX23ucOi7P86AfOKrPShS4ZU1geMGPET7RCzFM3K1WR+tQAYjkutmFf09koZR27gytJ70+1/rdxmIhq3Z1aI3ua+657nCsn3OvV1ezq+v0mjm/jZb2ZwM6SonDxcf6rPp1/Ux04seS34R9XKimhO0+3hoXrugstkolr4tC7rTMpS1BHtmisqbEu+WUuatZffEaxUMN5W9Dor01wOl5E3SUQVKfNxA0jyhPRfP8wqwQzApxDFHbZRZWTFXj+bLeMCD45QPqBRWrXlbxUej7pORuRzzJ9HfRIVcVfXH93eZ8klcEwajqS+vjOmVaC9Dj5CMzJLfzSHXGu+X4HDbsX4+XiCHDB9it+FkUqD+PnK0QwhpBFBeQaYTQyMbumdKUDuXL348JpX6imWKf/TPz0hZUny4EOM72oEGfwBKC5kbo+nRd64YKw
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: uksrc-cam-cluster-credentials
      namespace: capi-self
