---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: ska-src-gatekeeper
spec:
  values:
    gatekeeper:
      siteCapabilities:
        existingSecret: true
      services:
        - route: "/echo"
          namespace: ska-src-gatekeeper-echo
          prefix: "https://"
          service_name: "ska-src-gatekeeper-echo"
          ingress_host: "gatekeeper.ral-stage.uksrc.org"
          port: 8080
          uuid: "ac558c13-5d1d-4a99-ba98-0ecb6bb6cb1d"
        - route: "/soda"
          namespace: ska-src-soda
          prefix: "https://"
          service_name: "ska-src-soda"
          ingress_host: "gatekeeper.ral-stage.uksrc.org"
          port: 8080
          uuid: "85330965-d980-4fd8-9bf5-5e27a4467355"
        - route: "/preparedata"
          namespace: preparedata
          prefix: "https://"
          service_name: "preparedata-api"
          ingress_host: "gatekeeper.ral.uksrc.org"
          port: 8000
          uuid: "64c36212-0b7c-420a-89ba-c81088ce593e"          
    ingress-nginx:
      controller:
        replicaCount: 1
        service:
          type: ClusterIP
          loadBalancerIP: ""

          