apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: jupyterhub
spec:
  values:
    ingress:
      hosts:
      - jupyterhub.cam.uksrc.org
      tls:
        - hosts: 
          - jupyterhub.cam.uksrc.org
          secretName: jupyterhub-ingress-cert      
    hub:
      config:
        GenericOAuthenticator:
          oauth_callback_url: https://jupyterhub.cam.uksrc.org/hub/oauth_callback
          authorize_url: https://ska-iam.stfc.ac.uk/authorize
          token_url: https://ska-iam.stfc.ac.uk/token
          userdata_url: https://ska-iam.stfc.ac.uk/userinfo
        baseURL: https://jupyterhubcam.uksrc.org/jupyterhub